import { StyleSheet } from 'react-native';

const colors = {
  primary: '#1f145c',
  white: '#fff',
  yellow: '#FFFF00',
  lightBlue: '#add8e6',
  green: '#00a693',
  red: '#ff0000',
};

const Styles = StyleSheet.create({
  mainBlock: {
    marginTop: '20%',
    marginHorizontal: 12,
  },
  block: {
    height: '20%',
    backgroundColor: colors.lightBlue,
    width: '100%',
    position: 'absolute',
    top: 0,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 2,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: '15%',
    marginLeft: 30,
    marginRight: 30,
    elevation: 2,
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    backgroundColor: colors.lightBlue,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.52,
    shadowRadius: 10.22,
    elevation: 2,
  },
  input: {
    backgroundColor: colors.white,
    elevation: 40,
    flex: 1,
    height: 50,
    marginVertical: 20,
    marginRight: 20,
    borderRadius: 30,
    paddingHorizontal: 20,
  },
  iconAdd: {
    height: 50,
    width: 50,
    backgroundColor: colors.primary,
    borderRadius: 25,
    elevation: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  listItem: {
    padding: 20,
    backgroundColor: colors.white,
    flexDirection: 'row',
    elevation: 12,
    borderRadius: 7,
    marginVertical: 10,
  },
  checkBox: {
    height: 25,
    width: 25,
    backgroundColor: colors.white,
    borderColor: colors.red,
    borderWidth: 2,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 5,
    borderRadius: 3,
  },
  doneBox: {
    height: 25,
    width: 25,
    backgroundColor: colors.white,
    borderColor: colors.green,
    borderWidth: 2,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 5,
    borderRadius: 3,
  },
  undoneBox: {
    height: 25,
    width: 25,
    backgroundColor: colors.white,
    borderColor: colors.primary,
    borderWidth: 2,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 5,
    borderRadius: 3,
  },
  deleteBox: {
    height: 42,
    width: 40,
    backgroundColor: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 5,
    borderRadius: 3,
    borderColor: colors.red,
    borderWidth: 2,
  },
  buttonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: '3%',
    marginHorizontal: 10,
  },
  dropdown: {
    height: 40,
    width: 240,
    borderColor: colors.lightBlue,
    borderRadius: 3,
    backgroundColor: colors.lightBlue,
    color: colors.primary,
    paddingHorizontal: 13,
    fontSize: 17,
    fontWeight: 'bold',
  },
});

export default Styles;
